version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - mvn war:exploded
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - mv target/ROOT .
artifacts:
  type: zip
  files:
    - 'target/ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/Application.class'
    - 'target/ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/ServletInitializer.class'
    - 'target/ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/controllers/GreetingController.class'
    - 'target/ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/controllers/RequestController.class'
    - 'target/ROOT/WEB-INF/classes/com/robertsonwebdev/sunshadersrestservice/controllers/Response.class'
    - 'target/ROOT/WEB-INF/lib/attoparser-2.0.4.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/classmate-1.3.4.jar'
    - 'target/ROOT/WEB-INF/lib/evo-inflector-1.2.2.jar'
    - 'target/ROOT/WEB-INF/lib/hibernate-validator-6.0.9.Final.jar'
    - 'target/ROOT/WEB-INF/lib/jackson-annotations-2.9.0.jar'
    - 'target/ROOT/WEB-INF/lib/jackson-core-2.9.5.jar'
    - 'target/ROOT/WEB-INF/lib/jackson-databind-2.9.5.jar'
    - 'target/ROOT/WEB-INF/lib/jackson-datatype-jdk8-2.9.5.jar'
    - 'target/ROOT/WEB-INF/lib/jackson-datatype-jsr310-2.9.5.jar'
    - 'target/ROOT/WEB-INF/lib/jackson-module-parameter-names-2.9.5.jar'
    - 'target/ROOT/WEB-INF/lib/javax.annotation-api-1.3.2.jar'
    - 'target/ROOT/WEB-INF/lib/jboss-logging-3.3.2.Final.jar'
    - 'target/ROOT/WEB-INF/lib/jul-to-slf4j-1.7.25.jar'
    - 'target/ROOT/WEB-INF/lib/log4j-api-2.10.0.jar'
    - 'target/ROOT/WEB-INF/lib/log4j-to-slf4j-2.10.0.jar'
    - 'target/ROOT/WEB-INF/lib/logback-classic-1.2.3.jar'
    - 'target/ROOT/WEB-INF/lib/logback-core-1.2.3.jar'
    - 'target/ROOT/WEB-INF/lib/slf4j-api-1.7.25.jar'
    - 'target/ROOT/WEB-INF/lib/snakeyaml-1.19.jar'
    - 'target/ROOT/WEB-INF/lib/spring-aop-5.0.6.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-beans-5.0.6.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-boot-2.0.2.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-boot-autoconfigure-2.0.2.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-boot-devtools-2.0.2.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-boot-starter-2.0.2.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-boot-starter-data-rest-2.0.2.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-boot-starter-json-2.0.2.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-boot-starter-logging-2.0.2.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-boot-starter-thymeleaf-2.0.2.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-boot-starter-web-2.0.2.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-context-5.0.6.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-core-5.0.6.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-data-commons-2.0.7.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-data-rest-core-3.0.7.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-data-rest-webmvc-3.0.7.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-expression-5.0.6.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-hateoas-0.24.0.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-jcl-5.0.6.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-plugin-core-1.2.0.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-tx-5.0.6.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-web-5.0.6.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/spring-webmvc-5.0.6.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/thymeleaf-3.0.9.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/thymeleaf-extras-java8time-3.0.1.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/thymeleaf-spring5-3.0.9.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/unbescape-1.1.5.RELEASE.jar'
    - 'target/ROOT/WEB-INF/lib/validation-api-2.0.1.Final.jar'